[package]
name = "signal_box_sim"
version = "0.0.0"
edition = "2024"
description = "N/A"
readme = "README.md"
repository = "https://github.com/jonathan-schild/signal-box-sim"
license = "EUPL-1.2"
publish = false

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
thiserror = "2.0.12"